### ISSUE TITLE
Checklist du matériel

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/FabMob#7]
Context
--------
Il faut un checklist du matériel dans les modules. Ceci pour vérifier avant et après une activité si tout le matériel est là. 

Proposition
-----------
Coller une photo de la liste du matériel sur le couvercle de chaque module.
+ une liste des éléments dans le module
+ une obligation de soit remplir une papier, soit poster sur github les choses qu'il faut qu'on regarde.

**Comment by milenasonneveld** [comment]
*Module ordinateur*
![img_2147 1](https://user-images.githubusercontent.com/31619215/44547114-544b2800-a71a-11e8-944c-86c373e10748.JPG)

**Comment by milenasonneveld** [comment]
*Module impression 3D*
![img_2167 1](https://user-images.githubusercontent.com/31619215/44547138-6c22ac00-a71a-11e8-8e67-47e943a46596.JPG)
![img_2166 1](https://user-images.githubusercontent.com/31619215/44547152-70e76000-a71a-11e8-90de-6e21d3ddef59.JPG)

**Comment by milenasonneveld** [comment]
*Le fabvélo*
- [ ] Les clés et l'ordinateur de bord
- [ ] Le cadenas rouge, le cadenas en U
- [ ] La sangle bleue et la mousse protectrice

![img_2122](https://user-images.githubusercontent.com/31619215/44547370-2a463580-a71b-11e8-8d20-a30fa222c173.JPG)

**Comment by milenasonneveld** [comment]
*Extra*
- [ ] Les flyers du Fablab Mobile Brussels et les cartes de visite de Openfab et de Vélo M²

**Comment by nicolasdb** [comment]
Cool, j'avais commencé ça chez moi. https://github.com/nicolasdb/nicolasdb.github.io/issues/94
Je remet ici ce que j'avais fait.

## module 3D print
![image](https://user-images.githubusercontent.com/12049360/40847356-6f22a210-65bc-11e8-99cd-4b8fd62176d1.png)

- 2x Fabrikator v2
- 2x power supply Fabrikator v2
- 2x Multiprise noire OF
- 1x enrouleur multiprise
- 1x spatule
- 1x pince coupante
- 1x pince noire (type "à épiler")
- 1x rouleau de tape bleu (3Dprint)
- 2x bobines PLA + supports plastique
- 2x supports bobines metal
- 2x cable micro USB

**+ Extra**
![image](https://user-images.githubusercontent.com/12049360/40847390-8909244c-65bc-11e8-9b1d-b62d494bf821.png)

- Micro USB en rab
- 2x hub usb
- adaptateur usb>LAN pour lenovo
- adaptateur usb>microSD

## module PC
![image](https://user-images.githubusercontent.com/12049360/40847385-850cdac8-65bc-11e8-8966-3a63422befb7.png)

7x dell latitude
7x power supply dell
4x lenovo helix2
4x power supply lenovo
?x souris usb
2x tablettes graphique "bamboo wacom"
2x cable usb

**Comment by nicolasdb** [comment]
I'll close this one because it's resolved with #13 and #12 
great job
